{
 "title": "Forecast Hardware Usage",
 "time": { "from": "now-14d", "to": "now+14d" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } },
   {
    "name": "Host",
    "label": "Host",
    "query": {
     "query": "label_values({job=~\"$job\", instance=~\".*:9.*\"},instance)"
    }
   },
   { "name": "Period", "label": "Period (Days)", "query": "7, 14, 30, 90, 180" }
  ]
 },
 "panels": [
  { "title": "Panel Title", "type": "canvas", "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 } },
  {
   "title": "${Host} Прогноз CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=~\"${Host}\", mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=~\"${Host}\",}[$__rate_interval])))) * 100",
     "legendFormat": "Value"
    },
    {
     "columns": [
      { "selector": "ds", "text": "Time", "type": "timestamp" },
      { "selector": "yhat", "text": "Value", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "csv",
     "uql": "parse-csv",
     "url": "http://ENTER_FORECASTER_ADDRESS_HERE/forecast/cpu/",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "${Host} Прогноз RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((avg_over_time(node_memory_MemAvailable_bytes{instance=~\"${Host}\"}[$__rate_interval]) * 100) / avg_over_time(node_memory_MemTotal_bytes{instance=~\"${Host}\"}[$__rate_interval]))",
     "legendFormat": "Value"
    },
    {
     "columns": [
      { "selector": "ds", "text": "Time", "type": "timestamp" },
      { "selector": "yhat", "text": "Value", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "csv",
     "uql": "parse-csv",
     "url": "http://ENTER_FORECASTER_ADDRESS_HERE/forecast/ram/",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "${Host} Прогноз RootFS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((avg_over_time(node_filesystem_avail_bytes{instance=~\"$Host\",mountpoint=\"/\",fstype!=\"rootfs\"}[$__rate_interval]) * 100) / avg_over_time(node_filesystem_size_bytes{instance=~\"$Host\",mountpoint=\"/\",fstype!=\"rootfs\"}[$__rate_interval]))",
     "legendFormat": "Value"
    },
    {
     "columns": [
      { "selector": "ds", "text": "Time", "type": "timestamp" },
      { "selector": "yhat", "text": "Value", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "csv",
     "uql": "parse-csv",
     "url": "http://ENTER_FORECASTER_ADDRESS_HERE/forecast/disk/",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  }
 ]
}